[tool.poetry]
name = "langgaph-course"
version = "0.1.0"
description = ""
authors = ["Eden Marco <emarco177@gmail.com>"]
readme = "README.md"
packages = [{ include = "graph" }]

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.12.3"
python-dotenv = "^1.0.1"
pytest = "^8.2.0"
faiss-cpu = "^1.8.0.post1"
langchainhub = "^0.1.20"
langgraph-cli = "^0.1.52"
tavily-python = "^0.5.0"
langchain-community = "^0.3.0"
pypdf = "^5.0.0"
langgraph-checkpoint-sqlite = "^2.0.5"
langgraph = "^0.3.1"
langchain = "^0.3.19"
langchain-openai = "^0.3.7"
tiktoken = "^0.9.0"
isort = "^6.0.1"
black = "^25.1.0"
chromadb = "^0.6.3"
langchain-chroma = "^0.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"