[tool.poetry]
name = "langgaph-course"
version = "0.1.0"
description = ""
authors = ["Eden Marco <emarco177@gmail.com>"]
readme = "README.md"
packages = [{ include = "graph" }]

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "*"
python-dotenv = "*"
pytest = "*"
faiss-cpu = "*"
langchainhub = "*"
langgraph-cli = "*"
tavily-python = "*"
langchain-community = "*"
pypdf = "*"
langgraph-checkpoint-sqlite = "*"
langgraph = "*"
langchain = "*"
langchain-openai = "*"
tiktoken = "*"
isort = "*"
black = "*"
chromadb = "*"
langchain-chroma = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"